### PR TITLE
Upgrade Java  11 to 17

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://github.com/strimzi/test-container-images/issues/25

### CODE REVIEW

**Comment by scholzj** [comment]
@see-quick What is the impact if this uses Java 17 on the things such as Bridge based on Java 11? I assume no impact as long as it is only the container image using Java 17 and not the test container code itself?

**Comment by JiriOndrusek** [comment]
I was trying to make a camel-quarkus test for kafka run on FIPS. My work canbe seen here: https://github.com/apache/camel-quarkus/pull/6091
I was able to customize the image by installing java 17 during runtime.  I was able to run the tests on the FIPs system (when using j17). Of course I had to create a PKCS12 stores correctly.

**Comment by JiriOndrusek** [comment]
@scholzj I'm no expert on kafka. I just noticed that according to the blog post (from the summary), kafka requires J17 to run on fIPs. I tried to achieve this and from my perspective it works as expected. Therefore I proposed this PR with the fix.

**Comment by scholzj** [comment]
> @scholzj I'm no expert on kafka. I just noticed that according to the blog post (from the summary), kafka requires J17 to run on fIPs. I tried to achieve this and from my perspective it works as expected. Therefore I proposed this PR with the fix.

It is more about the OpenJDK 17 having many improvements in FIPS support rather than Kafka itself. But yes, the OpenJDK17 is important for this.

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
@JiriOndrusek Can you please fix the DCO signoff? The instructions should be under the Details link next to the DCO status in the PR status section.

**Comment by see-quick** [comment]
> I assume no impact as long as it is only the container image using Java 17 and not the test container code itself?

That's my guess also...as we know Java 17 is backward-compatible with Java 11 so code should run on Java 17 runtime without any problem.

**Review by see-quick — APPROVED** [review]

**Review by tombentley — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR. Sorry, it looks like it got forgotten for a long time :-(.

**Pull request merged**
