### PR TITLE
Add s390x support to Azure CI and images

### PR DESCRIPTION
**Pull request by kun-lu20**
This PR is to add s390x (multi-arch) support to Azure CI to build and push docker images.

The multi-arch images are built via QEMU and the generated kafka images have been verified in integration tests of Strimzi Kafka Bridge on s390x VM.

Signed-off-by: Kun-Lu <kun.lu@ibm.com>

### CODE REVIEW

**Comment by kun-lu20** [comment]
Hi @scholzj , I've changed the logic to build per-platform images with their own tags and create a complete manifest. Could you please take a look? Thanks!

**Review by scholzj — APPROVED** [review]
Thanks, this looks good.

**Review by Frawless — APPROVED** [review]

**Review by see-quick — APPROVED** [review]
Thanks for such contribution 👍

**Comment by kun-lu20** [comment]
Thanks @scholzj @Frawless @see-quick

**Comment by scholzj** [comment]
@kun-lu20 I think @see-quick plans to do a reelase soon, so it should get there.

**Comment by kun-lu20** [comment]
@scholzj Thanks for letting me know!

**Pull request merged**
